# Generated by Django 5.0.6 on 2026-06-14 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_tenant_gst_monthly_quota_tenant_gst_usage_this_month_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GstApiLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=64)),
                ('success', models.BooleanField(default=True)),
                ('gstin', models.CharField(blank=True, max_length=15)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gst_api_logs', to='accounts.apikey')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gst_api_logs', to='accounts.tenant')),
            ],
            options={
                'verbose_name': 'GST API call',
                'verbose_name_plural': 'GST API calls',
                'ordering': ['-created_at'],
            },
        ),
    ]
