"""
Django settings for DSCApi project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import base64
import hashlib
import os
import sys
from pathlib import Path

# When frozen (PyInstaller), keep writable data beside the .exe.
if getattr(sys, 'frozen', False):
    BASE_DIR = Path(sys.executable).parent
    BUNDLE_DIR = Path(sys._MEIPASS)
else:
    BASE_DIR = Path(__file__).resolve().parent.parent
    BUNDLE_DIR = BASE_DIR


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True' if not getattr(sys, 'frozen', False) else 'False').lower() == 'true'

# SECURITY WARNING: keep the secret key used in production secret!
_secret_key = os.environ.get('SECRET_KEY', '').strip()
if not _secret_key:
    if 'test' in sys.argv:
        _secret_key = 'django-test-secret-key-not-for-production-use'
    elif DEBUG and not getattr(sys, 'frozen', False):
        _secret_key = 'django-insecure-dev-only-change-me-in-env'
    elif getattr(sys, 'frozen', False):
        _secret_key = 'frozen-build-placeholder-not-used-for-crypto'
    else:
        from django.core.exceptions import ImproperlyConfigured

        raise ImproperlyConfigured('SECRET_KEY environment variable must be set.')
SECRET_KEY = _secret_key

_allowed_hosts = os.environ.get('ALLOWED_HOSTS') or os.environ.get('DSCAPI_ALLOWED_HOSTS')
if _allowed_hosts:
    ALLOWED_HOSTS = [host.strip() for host in _allowed_hosts.split(',') if host.strip()]
elif getattr(sys, 'frozen', False):
    ALLOWED_HOSTS = ['*']
else:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']

_csrf_origins = os.environ.get('CSRF_TRUSTED_ORIGINS', '')
if _csrf_origins:
    CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in _csrf_origins.split(',') if origin.strip()]
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'accounts',
    'signPdf',
    'usb_agent',
]

_allow_basic = os.environ.get('ALLOW_BASIC_AUTH', 'false').strip().lower()
ALLOW_BASIC_AUTH = _allow_basic == 'true'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'accounts.authentication.APIKeyAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'sign_pdf': os.environ.get('THROTTLE_SIGN_PDF', '60/hour'),
        'sign_pdf_burst': os.environ.get('THROTTLE_SIGN_PDF_BURST', '10/min'),
        'agent_pair': os.environ.get('THROTTLE_AGENT_PAIR', '20/hour'),
    },
}
if ALLOW_BASIC_AUTH:
    REST_FRAMEWORK['DEFAULT_AUTHENTICATION_CLASSES'].append(
        'rest_framework.authentication.BasicAuthentication',
    )

_cache_backend = os.environ.get('CACHE_BACKEND', '').strip()
if _cache_backend == 'database':
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
            'LOCATION': 'django_cache_table',
        }
    }
elif _cache_backend == 'locmem' or DEBUG:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'dscapi-cache',
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
            'LOCATION': 'django_cache_table',
        }
    }

RATELIMIT_DEFAULT_LIMIT = int(os.environ.get('RATELIMIT_DEFAULT_LIMIT', '10'))
RATELIMIT_DEFAULT_PERIOD = int(os.environ.get('RATELIMIT_DEFAULT_PERIOD', '900'))
VERIFY_EMAIL_TOKEN_HOURS = int(os.environ.get('VERIFY_EMAIL_TOKEN_HOURS', '24'))
PASSWORD_RESET_TOKEN_HOURS = int(os.environ.get('PASSWORD_RESET_TOKEN_HOURS', '2'))

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'DSCApi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'DSCApi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

_database_url = os.environ.get('DATABASE_URL')
if _database_url:
    import dj_database_url

    DATABASES = {'default': dj_database_url.config(default=_database_url, conn_max_age=600)}
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'
DISPLAY_TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = (BUNDLE_DIR / 'staticfiles') if getattr(sys, 'frozen', False) else (BASE_DIR / 'staticfiles')
MEDIA_URL = '/media/'
MEDIA_ROOT = (BUNDLE_DIR / 'media') if getattr(sys, 'frozen', False) else (BASE_DIR / 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Directory for PFX/P12 files referenced by pfx_path on /api/signpdf-pfx
PFX_CERTS_DIR = BASE_DIR / 'certs'

# Digital signature appearance on signed PDFs (platform defaults for all tenants)
SIGNATURE_ANCHOR_TEXT = os.environ.get('SIGNATURE_ANCHOR_TEXT', 'Authorised Signatory')
SIGNATURE_ICON = BUNDLE_DIR / 'signPdf' / 'assets' / 'green-tick.png'
SIGNATURE_BOX_MIN_WIDTH = 118
SIGNATURE_BOX_HEIGHT = 64
SIGNATURE_FONT_SIZE = 8
SIGNATURE_BOX_RIGHT_PADDING = 28
SIGNATURE_BOX_SHIFT_RIGHT = 15
SIGNATURE_BOX_GAP_ABOVE_LABEL = 2
SIGNATURE_BOX_SHIFT_DOWN_FITZ = 8
SIGNATURE_BOX_PAGE_MARGIN = 5
SIGNATURE_ICON_DISPLAY_WIDTH = 60
SIGNATURE_ICON_OVERLAP_INSET = 20
SIGNATURE_ICON_PADDING = 2

PORTAL_SIGN_MAX_UPLOAD_BYTES = int(os.environ.get('PORTAL_SIGN_MAX_UPLOAD_MB', '10')) * 1024 * 1024
API_SIGN_MAX_UPLOAD_BYTES = int(os.environ.get('API_SIGN_MAX_UPLOAD_MB', '10')) * 1024 * 1024
TRUSTED_PROXY_COUNT = int(os.environ.get('TRUSTED_PROXY_COUNT', '0'))

# SaaS settings
DEFAULT_MONTHLY_QUOTA = int(os.environ.get('DEFAULT_MONTHLY_QUOTA', '100'))

# USB DSC desktop agent
USB_AGENT_PAIRING_TTL_MINUTES = int(os.environ.get('USB_AGENT_PAIRING_TTL_MINUTES', '5'))
USB_AGENT_SIGN_JOB_TTL_MINUTES = int(os.environ.get('USB_AGENT_SIGN_JOB_TTL_MINUTES', '15'))
USB_AGENT_HEARTBEAT_TIMEOUT_SECONDS = int(os.environ.get('USB_AGENT_HEARTBEAT_TIMEOUT_SECONDS', '90'))
USB_AGENT_LOCAL_PORT = int(os.environ.get('USB_AGENT_LOCAL_PORT', '9765'))
_usb_agent_origins = os.environ.get('USB_AGENT_ALLOWED_ORIGINS', '').strip()
USB_AGENT_ALLOWED_ORIGINS = [
    origin.strip().rstrip('/')
    for origin in _usb_agent_origins.split(',')
    if origin.strip()
]
# Optional: serve a built installer (.exe/.msi) instead of the dev ZIP bundle.
USB_AGENT_INSTALLER_PATH = os.environ.get('USB_AGENT_INSTALLER_PATH', '').strip()
SITE_URL = os.environ.get('SITE_URL', 'http://127.0.0.1:8080')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@dscapi.local')

_email_backend = os.environ.get('EMAIL_BACKEND', '').strip()
if _email_backend:
    EMAIL_BACKEND = _email_backend
elif os.environ.get('EMAIL_HOST'):
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

if os.environ.get('EMAIL_HOST'):
    EMAIL_HOST = os.environ['EMAIL_HOST']
    EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
    EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
    EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'true').lower() == 'true'
    EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', 'false').lower() == 'true'
    EMAIL_TIMEOUT = int(os.environ.get('EMAIL_TIMEOUT', '30'))
    SERVER_EMAIL = DEFAULT_FROM_EMAIL

_encryption_key = os.environ.get('ENCRYPTION_KEY', '').strip()
if _encryption_key:
    ENCRYPTION_KEY = _encryption_key.encode() if isinstance(_encryption_key, str) else _encryption_key
elif DEBUG or getattr(sys, 'frozen', False):
    # Stable dev key — set ENCRYPTION_KEY in .env for persistent local data.
    ENCRYPTION_KEY = base64.urlsafe_b64encode(b'ig-esign-dev-fernet-key-32bytes!')
else:
    from django.core.exceptions import ImproperlyConfigured

    raise ImproperlyConfigured('ENCRYPTION_KEY must be set when DEBUG is false.')

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

if not DEBUG and not getattr(sys, 'frozen', False):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    _secure_cookies = os.environ.get('SECURE_COOKIES', 'true').lower() == 'true'
    SESSION_COOKIE_SECURE = _secure_cookies
    CSRF_COOKIE_SECURE = _secure_cookies
    SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = 'same-origin'
    SESSION_COOKIE_HTTPONLY = True
    SESSION_COOKIE_AGE = int(os.environ.get('SESSION_COOKIE_AGE', str(60 * 60 * 24 * 7)))
    SESSION_EXPIRE_AT_BROWSER_CLOSE = False
