# Generated by Django 5.0.6 on 2026-06-12 07:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_tenant_signature_style'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=120)),
                ('prefix', models.CharField(db_index=True, max_length=20)),
                ('token_hash', models.CharField(max_length=64)),
                ('agent_version', models.CharField(blank=True, max_length=40)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('token_present', models.BooleanField(default=False)),
                ('cert_cn', models.CharField(blank=True, max_length=200)),
                ('cert_expires_at', models.DateTimeField(blank=True, null=True)),
                ('paired_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('paired_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paired_agent_devices', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_devices', to='accounts.tenant')),
            ],
            options={
                'ordering': ['-paired_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentPairingCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=6)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_pairing_codes', to='accounts.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_pairing_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UsbSignJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('prepared', 'Prepared'), ('completed', 'Completed'), ('expired', 'Expired'), ('failed', 'Failed')], default='prepared', max_length=16)),
                ('encrypted_pdf', models.BinaryField()),
                ('hash_before', models.CharField(max_length=64)),
                ('hash_after', models.CharField(blank=True, max_length=64, null=True)),
                ('document_type', models.CharField(blank=True, max_length=32, null=True)),
                ('detected_keyword', models.CharField(blank=True, max_length=100, null=True)),
                ('detection_confidence', models.CharField(default='none', max_length=8)),
                ('placement_payload', models.JSONField()),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sign_jobs', to='usb_agent.agentdevice')),
                ('signing_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usb_sign_jobs', to='accounts.usagelog')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usb_sign_jobs', to='accounts.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usb_sign_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
