# Generated by Django 5.0.6 on 2026-06-12 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_tenant_signature_style'),
        ('usb_agent', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usbsignjob',
            name='api_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usb_sign_jobs', to='accounts.apikey'),
        ),
        migrations.AlterField(
            model_name='usbsignjob',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usb_sign_jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
