# Generated by Django 5.0.6 on 2026-06-14 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_multiple_signature_styles'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='gst_monthly_quota',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='tenant',
            name='gst_usage_this_month',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('gstin', models.CharField(blank=True, db_index=True, max_length=15)),
                ('pan', models.CharField(blank=True, max_length=10)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, choices=[('35', 'Andaman and Nicobar Islands'), ('37', 'Andhra Pradesh'), ('12', 'Arunachal Pradesh'), ('18', 'Assam'), ('10', 'Bihar'), ('04', 'Chandigarh'), ('22', 'Chhattisgarh'), ('26', 'Dadra and Nagar Haveli and Daman and Diu'), ('07', 'Delhi'), ('30', 'Goa'), ('24', 'Gujarat'), ('06', 'Haryana'), ('02', 'Himachal Pradesh'), ('01', 'Jammu and Kashmir'), ('20', 'Jharkhand'), ('29', 'Karnataka'), ('32', 'Kerala'), ('38', 'Ladakh'), ('31', 'Lakshadweep'), ('23', 'Madhya Pradesh'), ('27', 'Maharashtra'), ('14', 'Manipur'), ('17', 'Meghalaya'), ('15', 'Mizoram'), ('13', 'Nagaland'), ('21', 'Odisha'), ('34', 'Puducherry'), ('03', 'Punjab'), ('08', 'Rajasthan'), ('11', 'Sikkim'), ('33', 'Tamil Nadu'), ('36', 'Telangana'), ('16', 'Tripura'), ('09', 'Uttar Pradesh'), ('05', 'Uttarakhand'), ('19', 'West Bengal')], max_length=2)),
                ('pincode', models.CharField(blank=True, max_length=6)),
                ('primary_email', models.EmailField(blank=True, max_length=254)),
                ('primary_name', models.CharField(blank=True, max_length=120)),
                ('primary_mobile', models.CharField(blank=True, max_length=15)),
                ('secondary_email', models.EmailField(blank=True, max_length=254)),
                ('secondary_name', models.CharField(blank=True, max_length=120)),
                ('secondary_mobile', models.CharField(blank=True, max_length=15)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to='accounts.tenant')),
            ],
            options={
                'verbose_name': 'Company profile',
            },
        ),
    ]
