# Generated by Django 5.0.6 on 2026-06-09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_apikey_customer_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='quota_plan',
            field=models.CharField(
                choices=[
                    ('free', 'Free'),
                    ('pro', 'Pro'),
                    ('pro_plus', 'Pro+'),
                ],
                default='free',
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name='QuotaEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_at_grant', models.CharField(
                    choices=[('free', 'Free'), ('pro', 'Pro'), ('pro_plus', 'Pro+')],
                    max_length=20,
                )),
                ('purchased_limit', models.PositiveIntegerField()),
                ('carry_forward', models.PositiveIntegerField(default=0)),
                ('quota_limit', models.PositiveIntegerField()),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('status', models.CharField(
                    choices=[
                        ('active', 'Active'),
                        ('expired', 'Expired'),
                        ('superseded', 'Superseded'),
                        ('cancelled', 'Cancelled'),
                    ],
                    default='active',
                    max_length=20,
                )),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('granted_by', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='granted_quota_entitlements',
                    to=settings.AUTH_USER_MODEL,
                )),
                ('renewed_from', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='renewals',
                    to='accounts.quotaentitlement',
                )),
                ('tenant', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='quota_entitlements',
                    to='accounts.tenant',
                )),
            ],
            options={
                'ordering': ['-starts_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='quotaentitlement',
            constraint=models.UniqueConstraint(
                condition=models.Q(('status', 'active')),
                fields=('tenant',),
                name='uniq_active_quota_entitlement_per_tenant',
            ),
        ),
    ]
