# Generated by Django 5.0.6 on 2026-06-23 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_tenantinvite'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tenantinvite',
            new_name='accounts_te_tenant__11dded_idx',
            old_name='accounts_te_tenant__a0f2c1_idx',
        ),
    ]
